import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS2',
      link: {
        type: 'doc',
        id: 'Module-1-ROS2/week-01-intro-physical-ai',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Module-1-ROS2',
        },
      ],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: GAZEBO',
      link: {
        type: 'doc',
        id: 'Module-2-GAZEBO/week-06-gazebo-fundamentals',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Module-2-GAZEBO',
        },
      ],
      collapsible: true,
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 3: ISSAC',
      link: {
        type: 'doc',
        id: 'Module-3-ISSAC/week-08-isaac-intro',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Module-3-ISSAC',
        },
      ],
      collapsible: true,
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 4: VLA',
      link: {
        type: 'doc',
        id: 'Module-4-VLA/week-11-humanoid-development',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Module-4-VLA',
        },
      ],
      collapsible: true,
      collapsed: true,
    },
  ],
};

export default sidebars;
